from datetime import date, timedelta

def get_eventos():
    hoy = date.today()

    return [
        {
            "id": 1,
            "nombre": "Brunch en La Casona Gastronómica",
            "tipo": "Brunch / Comida",
            "barrio": "Piantini",
            "precio_aprox": 1200,
            "ambiente": ["tranquilo", "íntimo", "diurno"],
            "mood_fit": ["relajada", "creativa", "social"],
            "descripcion": "Brunch dominical con menú rotativo de cocina fusión dominicana. Terraza con jardín, sin música estridente.",
            "fecha": hoy + timedelta(days=2),
            "horario": "10:00 AM – 2:00 PM",
            "parqueo": True,
            "para_turista": False,
            "novedad": True,
        },
        {
            "id": 2,
            "nombre": "Taller de Cerámica — Casa de Arte Bellas",
            "tipo": "Taller Creativo",
            "barrio": "Gazcue",
            "precio_aprox": 1500,
            "ambiente": ["creativo", "íntimo", "diurno"],
            "mood_fit": ["creativa", "relajada"],
            "descripcion": "Taller de introducción a cerámica a mano. Cupo limitado a 10 personas. Incluye materiales.",
            "fecha": hoy + timedelta(days=3),
            "horario": "11:00 AM – 1:30 PM",
            "parqueo": False,
            "para_turista": False,
            "novedad": True,
        },
        {
            "id": 3,
            "nombre": "Mercado de Diseñadores — Acento",
            "tipo": "Mercado / Cultura",
            "barrio": "Naco",
            "precio_aprox": 0,
            "ambiente": ["social", "animado", "diurno"],
            "mood_fit": ["social", "curiosa", "creativa"],
            "descripcion": "Feria mensual de diseñadores y artesanos dominicanos. Entrada libre, consumo opcional.",
            "fecha": hoy + timedelta(days=4),
            "horario": "10:00 AM – 4:00 PM",
            "parqueo": True,
            "para_turista": False,
            "novedad": False,
        },
        {
            "id": 4,
            "nombre": "Jazz en el Patio — Hotel Boutique 1621",
            "tipo": "Música en Vivo",
            "barrio": "Zona Colonial",
            "precio_aprox": 800,
            "ambiente": ["íntimo", "nocturno", "cultural"],
            "mood_fit": ["relajada", "romántica", "social"],
            "descripcion": "Trío de jazz local en patio colonial. Drinks incluidos en entrada. Solo 40 personas.",
            "fecha": hoy + timedelta(days=5),
            "horario": "7:00 PM – 10:00 PM",
            "parqueo": False,
            "para_turista": False,
            "novedad": True,
        },
        {
            "id": 5,
            "nombre": "Clase de Salsa Urbana — Estudio Move",
            "tipo": "Baile / Actividad",
            "barrio": "Evaristo Morales",
            "precio_aprox": 600,
            "ambiente": ["energético", "social", "nocturno"],
            "mood_fit": ["social", "energética", "aventurera"],
            "descripcion": "Clase abierta para principiantes. No necesitas pareja. Música en vivo al final.",
            "fecha": hoy + timedelta(days=3),
            "horario": "6:00 PM – 8:00 PM",
            "parqueo": True,
            "para_turista": False,
            "novedad": False,
        },
        {
            "id": 6,
            "nombre": "Cine al Aire Libre — Parque Mirador",
            "tipo": "Cine / Cultura",
            "barrio": "Bella Vista",
            "precio_aprox": 300,
            "ambiente": ["tranquilo", "social", "nocturno"],
            "mood_fit": ["relajada", "social", "curiosa"],
            "descripcion": "Proyección de película latinoamericana en el parque. Lleva tu silla o manta.",
            "fecha": hoy + timedelta(days=6),
            "horario": "7:30 PM – 10:00 PM",
            "parqueo": True,
            "para_turista": False,
            "novedad": True,
        },
        {
            "id": 7,
            "nombre": "Ruta del Café Specialty — Tres Locales",
            "tipo": "Gastronomía / Tour",
            "barrio": "Piantini / Naco / Serralles",
            "precio_aprox": 900,
            "ambiente": ["íntimo", "cultural", "diurno"],
            "mood_fit": ["curiosa", "creativa", "relajada"],
            "descripcion": "Recorrido guiado por tres cafeterías specialty de SD. Aprende métodos de extracción y prueba single origins dominicanos.",
            "fecha": hoy + timedelta(days=4),
            "horario": "9:00 AM – 12:00 PM",
            "parqueo": True,
            "para_turista": False,
            "novedad": True,
        },
        {
            "id": 8,
            "nombre": "Club de Lectura — Librería Cuesta",
            "tipo": "Cultura / Social",
            "barrio": "Agora Mall",
            "precio_aprox": 0,
            "ambiente": ["tranquilo", "íntimo", "diurno"],
            "mood_fit": ["relajada", "curiosa"],
            "descripcion": "Discusión mensual de libro dominicano contemporáneo. Entrada libre, el libro lo consigues ahí mismo.",
            "fecha": hoy + timedelta(days=7),
            "horario": "4:00 PM – 6:00 PM",
            "parqueo": True,
            "para_turista": False,
            "novedad": False,
        },
    ]


MOODS = [
    {"label": "Relajada", "emoji": "🌿", "key": "relajada", "desc": "Quiero algo tranquilo, sin presión"},
    {"label": "Social", "emoji": "✨", "key": "social", "desc": "Quiero gente, conversación, energía"},
    {"label": "Creativa", "emoji": "🎨", "key": "creativa", "desc": "Quiero hacer algo con las manos o la mente"},
    {"label": "Curiosa", "emoji": "🔍", "key": "curiosa", "desc": "Quiero descubrir algo que no conozco"},
    {"label": "Energética", "emoji": "⚡", "key": "energética", "desc": "Quiero moverme, activarme"},
    {"label": "Aventurera", "emoji": "🗺️", "key": "aventurera", "desc": "Quiero salir de mi zona"},
]

PRESUPUESTOS = [
    {"label": "Hasta RD$500", "max": 500},
    {"label": "Hasta RD$1,000", "max": 1000},
    {"label": "Hasta RD$1,500", "max": 1500},
    {"label": "Sin límite", "max": 99999},
]
